# Generated by Django 5.0.3 on 2024-04-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asignar',
            field=models.CharField(choices=[('', 'sin asignar'), ('uno', 'Davis Hernandez'), ('dos', 'Libby Arias'), ('tres', 'Katherine Monterroso'), ('cuatro', 'Daniel Hall')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='categorias',
            field=models.CharField(choices=[('', 'sin categoria'), ('red', 'Red'), ('Impresoras', 'Impresoras'), ('Disco_duro', 'Disco duro'), ('Aplicaciones', 'Aplicaciones')], default='', max_length=30),
        ),
    ]
