# Generated by Django 5.0.3 on 2024-04-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticket_asignar_ticket_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='asignar',
            field=models.CharField(choices=[('', 'sin asignar'), ('Davis Hernandez', 'Davis Hernandez'), ('Libby Arias', 'Libby Arias'), ('Katherine Monterroso', 'Katherine Monterroso'), ('Daniel Hall', 'Daniel Hall')], default='', max_length=20),
        ),
    ]
