# Generated by Django 5.0.3 on 2024-05-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticket_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='body',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sender',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
