# Generated by Django 5.0.7 on 2024-09-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ticket_body_ticket_sender_ticket_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(max_length=100)),
                ('smtp_port', models.IntegerField()),
                ('smtp_user', models.EmailField(max_length=254)),
                ('email_host_password', models.CharField(max_length=100)),
            ],
        ),
    ]
