# Generated by Django 5.0.7 on 2024-09-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_email_host_password_configuracioncorreo_smtp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncorreo',
            name='smtp_host',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracioncorreo',
            name='smtp_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracioncorreo',
            name='smtp_user',
            field=models.CharField(max_length=255),
        ),
    ]
